import os
import re
import xml.etree.ElementTree as ET
from pathlib import Path

def generate_manifest():
    root_dir = Path(__file__).parent.parent
    assets_dir = root_dir / "assets"
    
    readme_path = root_dir / "README.md"
    preview_path = root_dir / "docs" / "visual-review.html"
    
    readme_content = open(readme_path, "r", encoding="utf-8").read() if readme_path.exists() else ""
    preview_content = open(preview_path, "r", encoding="utf-8").read() if preview_path.exists() else ""
    
    manifest_lines = [
        "# Asset Manifest",
        "This file is automatically generated. Do not edit manually.",
        "",
        "| Asset Path | Type | Dimensions/ViewBox | Size (bytes) | In README | In Preview | Orphaned |",
        "|---|---|---|---|---|---|---|"
    ]
    
    for file in assets_dir.rglob("*"):
        if not file.is_file():
            continue
        if file.name == ".keep":
            continue
            
        rel_path = file.relative_to(root_dir).as_posix()
        file_type = file.suffix.upper()[1:]
        size = file.stat().st_size
        
        dims = "N/A"
        if file.suffix.lower() == ".svg":
            try:
                tree = ET.parse(file)
                root = tree.getroot()
                if "viewBox" in root.attrib:
                    dims = root.attrib["viewBox"]
                elif "width" in root.attrib and "height" in root.attrib:
                    dims = f"{root.attrib['width']}x{root.attrib['height']}"
            except:
                dims = "Error parsing XML"
                
        in_readme = rel_path in readme_content
        in_preview = rel_path in preview_content or f"../{rel_path}" in preview_content
        orphaned = not (in_readme or in_preview)
        
        manifest_lines.append(f"| {rel_path} | {file_type} | {dims} | {size} | {'Yes' if in_readme else 'No'} | {'Yes' if in_preview else 'No'} | {'**Yes**' if orphaned else 'No'} |")
        
    val_dir = root_dir / "validation"
    val_dir.mkdir(exist_ok=True)
    
    with open(val_dir / "asset-manifest.generated.md", "w", encoding="utf-8") as f:
        f.write("\n".join(manifest_lines))
        
    print("Asset manifest generated at validation/asset-manifest.generated.md")

if __name__ == "__main__":
    generate_manifest()
